%
% NAME
%   nasa_fname - build a nasa product filename
%
% SYNOPSIS
%   fname = nasa_fname(prod_attr);
%
% INPUTS
%   prod_attr - all other product fields
%

function fname = nasa_fname(prod_attr);

% build the filename
fname = [ ...
  prod_attr.product_name_project,         '.', ...
  prod_attr.product_name_platform,        '.', ...
  prod_attr.product_name_instr,           '.', ...
  prod_attr.gran_id,                      '.', ...
  prod_attr.product_name_duration,        '.', ...
  prod_attr.product_name_granule_number,  '.', ...
  prod_attr.product_name_type_id,         '.', ...
  prod_attr.product_name_variant,         '.', ...
  prod_attr.product_name_version,         '.', ...
  prod_attr.product_name_producer,        '.', ...
  prod_attr.product_name_timestamp,       '.', ...
  prod_attr.product_name_extension];

